name: Indepth analysis
on: 
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: 
    branches: ["main"]
    paths:
     - .github/src/*
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
#         plugin_languages_ignored: >-
#           html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
#           gnuplot
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 20
#         plugin_languages_analysis_timeout: 15
