name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "5 0 * * 1,2,3,4,5,6"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
# push: 
#   branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: .github/src/github-metrics.svg
          base: header, activity, community
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/github-metrics2.svg
          base: repositories, discussions, metadata
          plugin_lines: yes
          plugin_traffic: yes
          plugin_discussions: yes
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            json
#           html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
#           gnuplot
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: disable
          plugin_languages_categories: data, markup, programming, prose
#         plugin_languages_analysis_timeout: 15
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.languages.recently-used.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 31
      - uses: lowlighter/metrics@master
        with:
          filename: .github/src/metrics.plugin.habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 300       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: no       # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: no        # Trim unused hours on daily chart
          config_timezone: Europe/Paris # Set timezone
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.followup.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_details: percentage
      - uses: lowlighter/metrics@latest
        with: 
          filename: .github/src/metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_shuffle_repositories: yes
          plugin_starlists_limit_languages: disable
          plugin_starlists_limit: 3
          plugin_starlists_limit_repositories: 3
      - uses: lowlighter/metrics@latest
        with: 
          filename: .github/src/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
#          plugin_achievements_only: >-
#            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
#            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 110
          plugin_skyline_quality: 0.8
          plugin_skyline_compatibility: no
