name: Recent activity charts
on: 
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: 
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no
          plugin_habits_trim: no        # Trim unused hours on daily chart
#         plugin_habits_from: 200       # Use 200 events to compute habits
#         plugin_habits_days: 14        # Keep only events from last 14 days
          config_timezone: Europe/Paris
