name: Skyline
on: 
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: 
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.skyline.svg
#         token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.8
          plugin_skyline_compatibility: yes
