name: TEST
on:
  # Schedule daily updates
  schedule: [{cron: "5 0 * * 1,2,3,4,5,6"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: 
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
#          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 20
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 31
